name: tell
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - cudatoolkit=11.6
  - cython>=0.29.21
  - ipykernel
  - matplotlib
  - mypy=0.750
  - numpy<2.0
  - pip
  - pillow
  - pytorch=1.12.1
  - python=3.9
  - pyyaml>=5.4
  - torchvision=0.13.1
  - pip:
      - allennlp==2.10.1
      - beautifulsoup4>=4.12
      - django==4.2
      - djangorestframework==3.14.0
      - django-cors-headers>=4.0
      - docopt==0.6.2
      - langdetect==1.0.9
      - nltk==3.8.1
      - overrides==7.4.0
      - opencv-python
      - ptvsd
      - pudb==2019.2
      # - git+git://github.com/salaniz/pycocoevalcap.git@a6b79b0fbd0f4f293634831e4e09405de2abc955
      - pymongo
      - pyzmq
      - gunicorn==20.0.4
      - schema==0.7.1
      - spacy<3.4
      - stop-words==2018.7.23
      - tensorboard>=2.15
      - textstat==0.6.0
      - termcolor==1.1.0
      - tqdm
      - transformers<4.21
      - facenet-pytorch
