name: tell
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - cudatoolkit=11.6
  - cython=0.29.15
  - ipykernel
  - matplotlib
  - mypy=0.750
  - numpy
  - pip
  - pillow
  - pytorch=1.12.1
  - python=3.8
  - pyyaml=5.1.2
  - torchvision=0.13.1
  - pip:
      - allennlp==2.10.1
      - beautifulsoup4==4.8.2
      - django==3.2
      - djangorestframework==3.14.0
      - django-cors-headers==3.13.0
      - docopt==0.6.2
      - langdetect==1.0.7
      - nltk==3.4.5
      - overrides==2.8.0
      - opencv-python==4.2.0.34
      - ptvsd==4.3.2
      - pudb==2019.2
      - git+git://github.com/salaniz/pycocoevalcap.git@a6b79b0fbd0f4f293634831e4e09405de2abc955
      - pymongo==3.10.1
      - pyzmq==19.0.0
      - gunicorn==20.0.4
      - schema==0.7.1
      - spacy==2.1.9
      - stop-words==2018.7.23
      - tensorboard==2.1.1
      - textstat==0.6.0
      - termcolor==1.1.0
      - tqdm==4.43.0
      - transformers==2.5.1
      - facenet-pytorch
